# 1. PCA

## 1) firm data

In [11]:
import pandas as pd

firm = pd.read_csv('C:/Users/DaBin/Desktop/대학원/2024-2/통계계산특론/PROJECT/data/전처리/firm_500.csv')
firm.head()

,ticker,gvkey,permno,sic,ret,exchcd,shrcd,adm,bm_ia,herf,...,rna,roa,roe,rsup,sgr,sp,date,ffi49,year,Founded
0,AAPL,1690,14593,3663,-0.022556,3.0,11.0,0.000088,2.172032,0.408549,...,0.023417,-0.022451,-0.059406,0.000007,0.174376,0.004747,1997-02-28,37,1997,1977
1,AAPL,1690,14593,3663,0.123077,3.0,11.0,0.000090,2.222156,0.408549,...,-0.004670,-0.022451,-0.059406,-0.000020,-0.162363,0.004857,1997-03-31,37,1997,1977
2,AAPL,1690,14593,3663,-0.068493,3.0,11.0,0.000079,1.949835,0.408549,...,0.017374,-0.022451,-0.059406,-0.000006,0.042429,0.004262,1997-04-30,37,1997,1977
3,AAPL,1690,14593,3663,-0.022059,3.0,11.0,0.000085,2.093205,0.408549,...,0.025886,-0.131991,-0.344023,0.000067,1.229803,0.004101,1997-05-31,37,1997,1977
4,AAPL,1690,14593,3663,-0.142857,3.0,11.0,0.000087,2.140420,0.408549,...,0.029650,-0.131991,-0.344023,0.000018,1.271352,0.004194,1997-06-30,37,1997,1977

In [ ]:
firm['month'] = pd.to_datetime(firm['date']).dt.month

#date 칼럼 drop
firm2 = firm.drop(columns=['ret','ticker','date','Founded'])

firm2.shape

(105721, 59)

In [ ]:
#pca n_components 

import warnings
from sklearn.decomposition import PCA

#month column 생성
firm['month'] = pd.to_datetime(firm['date']).dt.month

#date 칼럼 drop
firm2 = firm.drop(columns=['ret','ticker','date','Founded'])

#Founded 칼럼 값 여러개 있는 행에서 첫번째 연도만 추출 후 intger변환

#firm2['Founded'] = firm2['Founded'].str.slice(0,4).astype(int)


n_com = 2
pca = PCA(n_components = n_com)
pca_array = pca.fit_transform(firm2)
pca_df = pd.DataFrame(pca_array, index = firm2.index,
                      columns = [f"pca{num+1}" for num in range(n_com)])

pca_df.to_csv("C:/Users/DaBin/Desktop/대학원/2024-2/통계계산특론/PROJECT/data/전처리/PCA_firm_2.csv",index = False)

In [36]:
# Component 변동성 반영 비율
print(pca.explained_variance_ratio_)

[9.99988044e-01 7.65330806e-06]

## 2) Macroeconomic

In [1]:
import pandas as pd
macro = pd.read_csv('C:/Users/DaBin/Desktop/대학원/2024-2/통계계산특론/PROJECT/data/macroeconomic_97_22.csv')
macro.head()

,sasdate,RPI,W875RX1,DPCERA3M086SBEA,CMRMTSPLx,RETAILx,INDPRO,IPFPNSS,IPFINAL,IPCONGD,...,DNDGRG3M086SBEA,DSERRG3M086SBEA,CES0600000008,CES2000000008,CES3000000008,DTCOLNVHFNM,DTCTHFNM,INVEST,month,year
0,1/1/1997,9319.423,8035.8,66.148,949228.0,223481.0,77.6945,86.2680,84.1103,93.3828,...,69.924,67.084,13.64,15.46,12.99,89237.47,318279.13,900.4961,1,1997
1,2/1/1997,9349.477,8073.7,66.287,968611.0,225422.0,78.6120,87.1427,84.8745,93.8988,...,69.981,67.268,13.67,15.49,12.99,89838.70,318417.81,901.1697,2,1997
2,3/1/1997,9394.426,8112.3,66.465,969052.0,226161.0,79.1021,87.8300,85.6868,94.5642,...,69.789,67.448,13.70,15.46,13.04,88875.91,321671.10,912.7681,3,1997
3,4/1/1997,9402.274,8125.4,66.461,972290.0,224615.0,79.1683,87.6534,85.3584,93.6208,...,69.896,67.618,13.71,15.52,13.03,86699.46,327250.65,927.6827,4,1997
4,5/1/1997,9445.666,8169.7,66.503,972051.0,222929.0,79.6084,88.2776,86.0382,94.3271,...,69.683,67.683,13.76,15.58,13.07,88921.74,330125.91,923.9910,5,1997

In [3]:
macro.shape

(303, 125)

In [8]:
#pca n_components 

import numpy as np
import warnings
from sklearn.decomposition import PCA
import math

#sasdate 칼럼 drop
#macro = macro.drop('sasdate',axis = 1)



n_com = 50
pca = PCA(n_components = n_com)
pca_array = pca.fit_transform(macro)
pca_df = pd.DataFrame(pca_array, index = macro.index,
                      columns = [f"pca{num+1}" for num in range(n_com)])

pca_df.to_csv("C:/Users/DaBin/Desktop/대학원/2024-2/통계계산특론/PROJECT/data/전처리/PCA_macro_50.csv",index = False)

In [43]:
# Component 변동성 반영 비율
print(pca.explained_variance_ratio_)

[9.53585298e-01 2.31055572e-02 1.57170382e-02 4.02873814e-03
 2.18093501e-03 1.15305487e-03 1.50241473e-04 4.12016854e-05
 2.02457400e-05 1.47513296e-05]

----

# 2. LSTM

In [ ]:
macro = pd.read_csv('C:/Users/DaBin/Desktop/대학원/2024-2/통계계산특론/PROJECT/data/macroeconomic_97_22.csv')

In [14]:
macro.head()

,sasdate,RPI,W875RX1,DPCERA3M086SBEA,CMRMTSPLx,RETAILx,INDPRO,IPFPNSS,IPFINAL,IPCONGD,...,DNDGRG3M086SBEA,DSERRG3M086SBEA,CES0600000008,CES2000000008,CES3000000008,DTCOLNVHFNM,DTCTHFNM,INVEST,month,year
0,1/1/1997,9319.423,8035.8,66.148,949228.0,223481.0,77.6945,86.2680,84.1103,93.3828,...,69.924,67.084,13.64,15.46,12.99,89237.47,318279.13,900.4961,1,1997
1,2/1/1997,9349.477,8073.7,66.287,968611.0,225422.0,78.6120,87.1427,84.8745,93.8988,...,69.981,67.268,13.67,15.49,12.99,89838.70,318417.81,901.1697,2,1997
2,3/1/1997,9394.426,8112.3,66.465,969052.0,226161.0,79.1021,87.8300,85.6868,94.5642,...,69.789,67.448,13.70,15.46,13.04,88875.91,321671.10,912.7681,3,1997
3,4/1/1997,9402.274,8125.4,66.461,972290.0,224615.0,79.1683,87.6534,85.3584,93.6208,...,69.896,67.618,13.71,15.52,13.03,86699.46,327250.65,927.6827,4,1997
4,5/1/1997,9445.666,8169.7,66.503,972051.0,222929.0,79.6084,88.2776,86.0382,94.3271,...,69.683,67.683,13.76,15.58,13.07,88921.74,330125.91,923.9910,5,1997

In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf

from tensorflow.keras.layers import Dense, Dropout, LSTM, Activation
from tensorflow.keras.models import Sequential
from tensorflow.keras.losses import MSE

In [ ]:
macro = macro.drop('sasdate',axis = 1)
macro = np.reshape(macro,(323,1,124)) 
 
# 모델 정의
model = Sequential([
    LSTM(units=64, activation='relu', input_shape=(1,124)),  # 시퀀스 요약
    Dense(32, activation='relu'),
    Dropout(0.2),
    Dense(10, activation='linear')  # 차원 축소: 최종 출력 차원 10
])

# 모델 컴파일
model.compile(optimizer='adam', loss='mse')

# 출력 확인
output = model.predict(macro)
print("Input shape:", macro.shape)  
print("Output shape:", output.shape)

In [ ]:
lstm_10 = pd.DataFrame(output, 
                      columns = [f"LSTM{num+1}" for num in range(10)])

In [25]:
! python -m pip install tensorflow

ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

In [21]:
def analyze_feature_importance(model, X, num_samples=1000):

    baseline_pred = model.predict(X)

    importances = []

    for feature_idx in range(X.shape[2]):

        X_perturbed = X.copy()
        X_perturbed[:, :, feature_idx] = np.random.permutation(X_perturbed[:, :, feature_idx])


        perturbed_pred = model.predict(X_perturbed)


        importance = np.mean(np.abs(perturbed_pred - baseline_pred))
        importances.append(importance)

    return importances


import pandas as pd
import numpy as np
import tensorflow as tf

from tensorflow.keras import layers
from tensorflow.keras.layers import Dense, Dropout, LSTM, Activation
from tensorflow.keras.models import Sequential
from tensorflow.keras.losses import MSE


#sasdate column drop

macro = macro.drop('sasdate',axis = 1)


X_train =  macro.drop('S&P 500', axis = 1)
y_train =  macro['S&P 500']



X_train = np.reshape(X_train,(303,1,123))


model = Sequential([layers.Input((1,123)),
                    layers.LSTM(64),
                    layers.Dense(32, activation='relu'),
                    Dropout(0.2),
                    layers.Dense(32, activation='relu'),
                    Dropout(0.2),
                    layers.Dense(1),
                ])

model.compile(optimizer='adam', loss='mse')
model.summary()


model.fit(X_train,y_train)
importances = analyze_feature_importance(model, X_train)
top_10 = np.argsort(importances)[::-1][:10]
top_30 = np.argsort(importances)[::-1][:30]
top_50 = np.argsort(importances)[::-1][:50]

col_10 = macro.columns[top_10]
macro[col_10].to_csv("/content/drive/MyDrive/계특 프로젝트/차원 축소 데이터/macro/LSTM_macro_10.csv")

col_30 = macro.columns[top_30]
macro[col_30].to_csv("/content/drive/MyDrive/계특 프로젝트/차원 축소 데이터/macro/LSTM_macro_30.csv")

col_50 = macro.columns[top_50]
macro[col_50].to_csv("/content/drive/MyDrive/계특 프로젝트/차원 축소 데이터/macro/LSTM_macro_50.csv")

ModuleNotFoundError: No module named 'tensorflow'